### ISSUE TITLE
Returncode is always `0`

### ISSUE THREAD

**Issue by ellcs** [OSInside/kiwi-boxed-plugin#35]
I got two pennies and can build faster now. But i ran into another issue. Our scripts depend on  `kiwi-ng`s return code. But it always returns 0: 

### Steps to reproduce

1. Setup as described in the documentation.
2. Clone kiwi-descriptions.
3. Create an error, two options exist:
  3a. `echo "exit 42" >> kiwi-descriptions/suse/x86_64/suse-leap-15.2/config.sh`
  3b. Syntax Error in `config.xml`: `echo "<<<<<" >> kiwi-descriptions/suse/x86_64/suse-leap-15.2/config.xml`
4. Trigger build
5. `echo $?`

### Expected behavior

Step 5 must not print 0. Build has been triggered with: 

```
kiwi-ng --type iso system boxbuild --box leap -- --description ~/kiwi-descriptions/suse/x86_64/suse-leap-15.2 --target-dir /tmp/myimage
```

It should work the same way as the classical build, which does not print 0.

### Actual behavior

Step 5 prints 0. Which contradictively indicates that the build was successful.

**Comment by schaefi** [comment]
Hi, I see. I'm afraid this will be not so easy to solve. When using boxbuild you are actually calling:

```
QEMU -> VM -> kiwi -> VM(stop)
```

The exit code of this chain of processes is the exit code of the QEMU call. Thus even if kiwi fails inside of the VM it will still end in a exit code == 0 because the VM itself was started and stopped without errors.

I think we need to expose the kiwi exit code on the shared folder, read it in after the VM has stopped and return with that exit code.

Let's try that
