### ISSUE TITLE
universal box build missing debootstrap support for ubuntu noble

### ISSUE THREAD

**Issue by kagehisa** [OSInside/kiwi-boxed-plugin#68]
I used the universal box build for a little over a week now with no issues. But starting today I can not build a Ubuntu 24.04 Image with the universal build vm.

```
kiwi-ng --profile MS-HyperV system boxbuild --box universal -- --description ./ubuntu --target-dir ./out
```

The `result.log` states that the installed debootstrap script does not support Ubuntu Noble.

>  [ INFO    ]: 06:59:21 | --> Alias: noble
[ INFO    ]: 06:59:21 | Using package manager backend: apt
[ INFO    ]: 06:59:21 | Installing bootstrap packages
[ INFO    ]: 06:59:21 | --> collection type: onlyRequired
[ INFO    ]: 06:59:21 | --> package: apt
[ ERROR   ]: 06:59:21 | KiwiDebootstrapError: debootstrap script for noble distribution not found

It was working fine for the previous builds and there was no change on the build system or the image description.

**Comment by schaefi** [comment]
Hmm, yes looks like.

I checked on the Universal box and that box builds against Fedora:Rawhide,
the latest and greates. The Version of debootstrap that gets pulled in
is this one:

```
<bdep name="debootstrap" version="1.0.136" release="1.fc41" arch="noarch" hdrmd5="6effc3a56836f89ca7fd952d9e41da4c" project="Fedora:Rawhide" repository="standard"/>
```

Unfortunately there is not much I can do to fix this. Is there a project
that always builds and maintains a debootstrap package that contains all
debootstrap scripts for all Debian and Debian derivatives ? If yes we
can point the build of the box to it.

In this particular case I think we need to reach out to the maintainers
of debootstrap in Fedora and ask if they can add noble back

>    I also openend a Github Issue for the case, just to be consistent.

Yep saw it, thanks I'll add my share to the thread and maybe Neal
knows what happened because I can also remember that I build for "noble"
using boxbuild

**Comment by schaefi** [comment]
@Conan-Kudo Do you have an idea why noble is no longer part of the debootstrap package in RawHide ?

**Comment by Conan-Kudo** [comment]
Well, we just update to new versions of `debootstrap` as they come automatically, so this is a problem with upstream Debian. Looking further upstream, [it looks like all the codename symlinks were deleted](https://salsa.debian.org/installer-team/debootstrap/-/commit/2d3eae916af51cc49ab0989cea1f5bfb58012179) in 1.0.135, but we didn't get this until 1.0.136 was released and built in Fedora. [Debian's was restored](https://salsa.debian.org/installer-team/debootstrap/-/commit/cf55650623a4a87ab353a7a89fa18debca239f5f) in 1.0.136, but [Ubuntu's symlinks were restored after that](https://salsa.debian.org/installer-team/debootstrap/-/commit/126c7713c5e641c0afeb060ef95bd3ee88b8faf1), and there's no release yet including it.

Let me reach out to the maintainer to request a new release to pull into Fedora.

**Comment by schaefi** [comment]
Awesome debugging, thanks much :+1:

**Comment by schaefi** [comment]
@kagehisa so at best this self heals

**Comment by kagehisa** [comment]
Thank you, I will pause our build pipeline atm. and will try again in a few days. 
Thanks a lot for the detailed analysis of the problem @Conan-Kudo !

**Comment by kagehisa** [comment]
Ok, this problem is solved. Thanks for your patience.

**Comment by schaefi** [comment]
@kagehisa yeah we no longer use debootstrap in kiwi and that should have fixed this one too. Thanks for the positive feedback, much appreciated
