### ISSUE TITLE
Lightweight box using bubblewrap

### ISSUE THREAD

**Issue by septatrix** [OSInside/kiwi-boxed-plugin#69]
Bubblewrap is a great sandboxing and namespacing tool which is used by e.g. flatpak and mkosi. The latter is also an image builder and uses it to enable unprivileged users to build images. This could be a great, lightweight alternative to spawning a VM for every build. It also makes file management easier as one does not have to use virtiofs or similar mechanisms.

**Comment by Conan-Kudo** [comment]
It doesn't work for loops and dm devices and all the other weird things that essentially force us to use a VM. The reason mkosi gets away with it is because it outright avoids using privileged stuff, so it can operate unprivileged (at the cost of not being able to produce some kinds of images). We are not able to do that in kiwi.

**Comment by septatrix** [comment]
It could still work for other output formats though, right? Especially container images and WSL images do not require loopback devices. This would still be quite useful.
Bear in mind that mkosi also requires root for certain configurations like partitions with subvolumes. There are then invoked from outside bwrap.

Or is this something which should better be discussed over at the kiwi repo, "this" meaning making rootless builds for non-exotic setups possible.

**Comment by Conan-Kudo** [comment]
You could run kiwi in a container already if you already know your target type will work though? What benefit would there be for a bubblewrap environment variant?
