### ISSUE TITLE
Usage of ubuntu 22.04 in kiwi-boxed-plugin

### ISSUE THREAD

**Issue by KhazAkar** [OSInside/kiwi-boxed-plugin#70]
Hi,
In kiwi-boxed-plugin.yml config, we have OBS link, which points to 23.04, but I need to build 22.04 image. Is there a way to access older image which was based on 22.04? Due to Azure IoT Edge agent OS support limitations for native .debs (22.04 at most), I need to use it :)

**Comment by schaefi** [comment]
@KhazAkar sorry this is a very late response but I believe it's still good information for you.

So in the past we used debootstrap to bootstrap a Debian/Ubuntu system and that has a direct impact on the version of the box file because only the available bootstrap scripts from debootstrap could be used to build the target distribution. We have changed this in kiwi such that we also bootstrap via apt and not via an extra debootstrap tool. This has the nice advantage that the version of the box is no longer coupled with the target you want to build.

That having said with the latest version of the box plugin you should be able to also build jammy (22.04) ubuntu images.
If you happen to have issues with that please open a new issue here.

Thanks much and again sorry for the very late response
